# Generated by Django 4.0.6 on 2022-09-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=64)),
                ('excel_file_path', models.FileField(upload_to='excel_file_path')),
            ],
        ),
    ]
