# Generated by Django 4.0.6 on 2022-09-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovysimulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='folder_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
