# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PicNum
                                 A QGIS plugin
 Load hysplit retros for pm > 80
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-02
        copyright            : (C) 2020 by Kwabena Kimia
        email                : fbrute@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PicNum class from file PicNum.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pic_num import PicNum
    return PicNum(iface)
